/*
Author Name: Edbert Jensen
Program Name: EECS 348 Assignment 1
Brief description: C program that picks a secret number between 1 and 10. The user gets up to 3 tries to guess the number
Inputs: 3 guesses from user
Outputs: ask user to enter number from 1-10. tell user if guess was correct, high or low, and game over if all guesses were incorrect.
Collaborators: Gemini Pro
Other sources: 
Creation date: 9/8/2026 7:21PM
Revision date: 9/8/2026 10:34PM
Revisions: add line by line comments and label AI generated comments if any
*/

// source code generated by gemini Pro
#include <stdio.h>         // import standard input output library

int main() {               // main function that takes no params.
    // <label> Fixed secret number as required
    int secret_number = 7;  // set secret num to 7
    int guess;              // initialize guess to no constant
    int max_attempts = 3;   // initialize max_attempts to 3 
    int won = 0;            // won set to 0(false) since bool type does not exist

    printf("Welcome to the Guessing Game!\n");                          // print welcome message
    printf("I have picked a secret number between 1 and 10.\n");        // tell user that a number has been picked
    printf("You have %d attempts to guess it.\n\n", max_attempts);      // print max attempts of guesses

    // <label> Loop lets the user guess up to 3 times
    for (int attempt = 1; attempt <= max_attempts; attempt++) {         // for loop that iterates 3 times, the test is attempt constant has to be lesser than or equal to 3
        printf("Attempt %d: Enter your guess: ", attempt);              // print attempt number and ask user
        
        // <label> Read the user's guess
        scanf("%d", &guess);            // read user input and reintialize guess constant

        // <label> Check if the guess is correct, too high, or too low
        if (guess == secret_number) {   // if statement that checks if guess is equal to secret number
            won = 1;                    // set won to 1(true)
            break; // <label> Stop the loop immediately on a correct guess
        } else if (guess > secret_number) {     // else if statement that checks guess greater than secret number
            printf("Too high!\n");              // print Too high!
        } else {                                // else statement that checks anything lesser than secret number
            printf("Too low!\n");               // print Too low!
        }
    }

    // <label> Final win or lose message
    printf("\n");
    if (won) {                                  // check if won is 1(true)
        printf("Congratulations, you win! You guessed the secret number.\n");   // print congratulation message
    } else {                                    // check otherwise (won is 0(false))
        printf("Game over. You lose! The secret number was %d.\n", secret_number);  //prtin game over and tell user the secret number
    }

    return 0;
}