/*
Author Name: Edbert Jensen
Program Name: EECS 348 Assignment 1
Brief description: C program that picks a secret number between 1 and 10. The user gets up to 3 tries to guess the number
Inputs: 3 guesses from user
Outputs: ask user to enter number from 1-10. tell user if guess was correct, high or low, and game over if all guesses were incorrect.
Collaborators: qwen3:1.7b
Other sources: Gemini Pro
Creation date: 9/8/2026 7:21PM
Revision date: 9/8/2026 10:41PM
Revisions: add improvement changes stated in the analysis
*/

// all code is generated by qwen3:1.7b
#include <stdio.h>                  // import standard input output library

int main() {                        // main function takes no params
    int secret = 7;                 // secret is 7
    int guess = 0;                  // guess is 0
    int max_attempts = 3;               // max_attempts set to 3

    for(int attempt = 0; attempt < max_attempts; attempt++) {          // repetition while statement that test if attempts is lesser than 0
        printf("Enter your guess (1-10): ");        // ask user to enter the guess
        // generated by Gemini Pro
        if (scanf("%d", &guess) != 1) {             // scan the user number
            printf("Error: That is not a valid integer. Please try again.\n");  // output error to user     
            
            // <label> Clear the invalid characters from the input buffer
            int c;
            while ((c = getchar()) != '\n' && c != EOF) {
                // <label> Do nothing, just consume the characters
            }
            
            // <label> Subtract 1 from attempt so the user doesn't lose a turn for a typo
            attempt--; 
            continue;
        }                      

        if (guess == secret) {                      // if guess equals to secret
            printf("Win! You guessed the correct number.\n");       // then print win
            break;                                  // break out of while loop
        } else if (guess > secret) {                // else if guess is greater than secret
            printf("Too high! Try again.\n");       // then print Too high! Try again
        } else {                                    // otherwise
            printf("Too low! Try again.\n");        // print Too low! Try again
        }
    }

    if (guess != secret) {                                                  // checks final guess against secret if they are not equal
        printf("Game Over! You failed to guess the correct number.\n");     // then print game over message
    }
    return 0;
}
